### ISSUE TITLE
[bug] No dropdown menu options on navbar

### ISSUE THREAD

**Issue by crmejia** [thiagonache/morningpost#36]
What happened:

There app's Navbar doesn't have menu options in the drop down menu:
![Screenshot 2023-05-08 at 8 39 20 PM](https://github.com/thiagonache/morningpost/assets/4006175/671f3589-cef6-4fe3-ae7c-499536907148)

Expected:
To see some options or not see the menu at all.

Setup:
I'm running Firefox `111.0.1`

**Comment by thiagonache** [comment]
Hi @crmejia,

Thank you for reporting this issue!
While I'm working on it, as a workaround, you can expand the window size and the dropdown should disappear and the menu is going to be shown in the navbar.

**Comment by thiagonache** [comment]
fixed via #37
